// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function se(prim) {
  return prim;
}

function DummyComponent(Props) {
  var title = Props.title;
  var match = React.useReducer((function (state, action) {
          return {
                  clicked: !state.clicked
                };
        }), {
        clicked: false
      });
  var dispatch = match[1];
  return React.createElement("div", {
              className: "dummy"
            }, React.createElement("div", {
                  id: "header"
                }, React.createElement("h1", undefined, title)), React.createElement("div", {
                  id: "content"
                }, React.createElement("button", {
                      id: "click-me",
                      onClick: (function (_event) {
                          return Curry._1(dispatch, /* Click */0);
                        })
                    }, match[0].clicked ? "I've been clicked!" : "Click Me!"), React.createElement("ul", {
                      id: "list"
                    }, React.createElement("li", undefined, "One"), React.createElement("li", undefined, "Two"), React.createElement("li", undefined, "Three"))));
}

var make = DummyComponent;

export {
  se ,
  make ,
  
}
/* react Not a pure module */
