// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Enzyme from "enzyme";

function state(t) {
  return t.state().reasonState;
}

var Renderer = {
  state: state
};

var Shallow = {
  state: state
};

var Mount = {
  state: state
};

function configureEnzyme(adapter) {
  return Enzyme.configure({
              adapter: adapter
            });
}

export {
  Renderer ,
  Shallow ,
  Mount ,
  configureEnzyme ,
  
}
/* enzyme Not a pure module */
